"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_outgoing_caller_id import ApiV2010AccountOutgoingCallerId
globals()['ApiV2010AccountOutgoingCallerId'] = ApiV2010AccountOutgoingCallerId
from openapi_client.model.inline_response20031 import InlineResponse20031


class TestInlineResponse20031(unittest.TestCase):
    """InlineResponse20031 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20031(self):
        """Test InlineResponse20031"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20031()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
