"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_incoming_phone_number import ApiV2010AccountIncomingPhoneNumber
globals()['ApiV2010AccountIncomingPhoneNumber'] = ApiV2010AccountIncomingPhoneNumber
from openapi_client.model.inline_response20021 import InlineResponse20021


class TestInlineResponse20021(unittest.TestCase):
    """InlineResponse20021 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20021(self):
        """Test InlineResponse20021"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20021()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
