"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record_usage_record_daily import ApiV2010AccountUsageUsageRecordUsageRecordDaily
globals()['ApiV2010AccountUsageUsageRecordUsageRecordDaily'] = ApiV2010AccountUsageUsageRecordUsageRecordDaily
from openapi_client.model.inline_response20053 import InlineResponse20053


class TestInlineResponse20053(unittest.TestCase):
    """InlineResponse20053 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20053(self):
        """Test InlineResponse20053"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20053()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
