"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_sip_sip_ip_access_control_list_sip_ip_address import ApiV2010AccountSipSipIpAccessControlListSipIpAddress
globals()['ApiV2010AccountSipSipIpAccessControlListSipIpAddress'] = ApiV2010AccountSipSipIpAccessControlListSipIpAddress
from openapi_client.model.inline_response20047 import InlineResponse20047


class TestInlineResponse20047(unittest.TestCase):
    """InlineResponse20047 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20047(self):
        """Test InlineResponse20047"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20047()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
