"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_outgoing_caller_id import ApiV2010AccountOutgoingCallerId


class TestApiV2010AccountOutgoingCallerId(unittest.TestCase):
    """ApiV2010AccountOutgoingCallerId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV2010AccountOutgoingCallerId(self):
        """Test ApiV2010AccountOutgoingCallerId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV2010AccountOutgoingCallerId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
