"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_signing_key import ApiV2010AccountSigningKey
globals()['ApiV2010AccountSigningKey'] = ApiV2010AccountSigningKey
from openapi_client.model.inline_response20049 import InlineResponse20049


class TestInlineResponse20049(unittest.TestCase):
    """InlineResponse20049 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20049(self):
        """Test InlineResponse20049"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20049()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
