"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_incoming_phone_number_incoming_phone_number_toll_free import ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberTollFree
globals()['ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberTollFree'] = ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberTollFree
from openapi_client.model.inline_response20024 import InlineResponse20024


class TestInlineResponse20024(unittest.TestCase):
    """InlineResponse20024 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20024(self):
        """Test InlineResponse20024"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20024()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
