"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_available_phone_number_country_available_phone_number_voip import ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberVoip
globals()['ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberVoip'] = ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberVoip
from openapi_client.model.inline_response20012 import InlineResponse20012


class TestInlineResponse20012(unittest.TestCase):
    """InlineResponse20012 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20012(self):
        """Test InlineResponse20012"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20012()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
