"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_incoming_phone_number_incoming_phone_number_mobile import ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile


class TestApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile(unittest.TestCase):
    """ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile(self):
        """Test ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
