"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record_usage_record_this_month import ApiV2010AccountUsageUsageRecordUsageRecordThisMonth
globals()['ApiV2010AccountUsageUsageRecordUsageRecordThisMonth'] = ApiV2010AccountUsageUsageRecordUsageRecordThisMonth
from openapi_client.model.inline_response20056 import InlineResponse20056


class TestInlineResponse20056(unittest.TestCase):
    """InlineResponse20056 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20056(self):
        """Test InlineResponse20056"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20056()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
