"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_call_call_notification import ApiV2010AccountCallCallNotification
globals()['ApiV2010AccountCallCallNotification'] = ApiV2010AccountCallCallNotification
from openapi_client.model.inline_response20015 import InlineResponse20015


class TestInlineResponse20015(unittest.TestCase):
    """InlineResponse20015 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20015(self):
        """Test InlineResponse20015"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20015()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
