"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_call import ApiV2010AccountCall
globals()['ApiV2010AccountCall'] = ApiV2010AccountCall
from openapi_client.model.inline_response20013 import InlineResponse20013


class TestInlineResponse20013(unittest.TestCase):
    """InlineResponse20013 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20013(self):
        """Test InlineResponse20013"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20013()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
