"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_call_call_event import ApiV2010AccountCallCallEvent
globals()['ApiV2010AccountCallCallEvent'] = ApiV2010AccountCallCallEvent
from openapi_client.model.inline_response20014 import InlineResponse20014


class TestInlineResponse20014(unittest.TestCase):
    """InlineResponse20014 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20014(self):
        """Test InlineResponse20014"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20014()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
