"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_message import ApiV2010AccountMessage
globals()['ApiV2010AccountMessage'] = ApiV2010AccountMessage
from openapi_client.model.inline_response20028 import InlineResponse20028


class TestInlineResponse20028(unittest.TestCase):
    """InlineResponse20028 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20028(self):
        """Test InlineResponse20028"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20028()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
