"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_available_phone_number_country_available_phone_number_shared_cost import ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberSharedCost
globals()['ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberSharedCost'] = ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberSharedCost
from openapi_client.model.inline_response20010 import InlineResponse20010


class TestInlineResponse20010(unittest.TestCase):
    """InlineResponse20010 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20010(self):
        """Test InlineResponse20010"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20010()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
