"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_connect_app import ApiV2010AccountConnectApp


class TestApiV2010AccountConnectApp(unittest.TestCase):
    """ApiV2010AccountConnectApp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV2010AccountConnectApp(self):
        """Test ApiV2010AccountConnectApp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV2010AccountConnectApp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
