"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_available_phone_number_country_available_phone_number_toll_free import ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberTollFree
globals()['ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberTollFree'] = ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberTollFree
from openapi_client.model.inline_response20011 import InlineResponse20011


class TestInlineResponse20011(unittest.TestCase):
    """InlineResponse20011 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20011(self):
        """Test InlineResponse20011"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20011()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
