"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_recording_recording_add_on_result_recording_add_on_result_payload import ApiV2010AccountRecordingRecordingAddOnResultRecordingAddOnResultPayload
globals()['ApiV2010AccountRecordingRecordingAddOnResultRecordingAddOnResultPayload'] = ApiV2010AccountRecordingRecordingAddOnResultRecordingAddOnResultPayload
from openapi_client.model.inline_response20037 import InlineResponse20037


class TestInlineResponse20037(unittest.TestCase):
    """InlineResponse20037 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20037(self):
        """Test InlineResponse20037"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20037()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
