"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_application import ApiV2010AccountApplication
globals()['ApiV2010AccountApplication'] = ApiV2010AccountApplication
from openapi_client.model.inline_response2003 import InlineResponse2003


class TestInlineResponse2003(unittest.TestCase):
    """InlineResponse2003 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003(self):
        """Test InlineResponse2003"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
