"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_sip_sip_domain_sip_auth_sip_auth_calls_sip_auth_calls_credential_list_mapping import ApiV2010AccountSipSipDomainSipAuthSipAuthCallsSipAuthCallsCredentialListMapping


class TestApiV2010AccountSipSipDomainSipAuthSipAuthCallsSipAuthCallsCredentialListMapping(unittest.TestCase):
    """ApiV2010AccountSipSipDomainSipAuthSipAuthCallsSipAuthCallsCredentialListMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV2010AccountSipSipDomainSipAuthSipAuthCallsSipAuthCallsCredentialListMapping(self):
        """Test ApiV2010AccountSipSipDomainSipAuthSipAuthCallsSipAuthCallsCredentialListMapping"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV2010AccountSipSipDomainSipAuthSipAuthCallsSipAuthCallsCredentialListMapping()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
