"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_trigger import ApiV2010AccountUsageUsageTrigger
globals()['ApiV2010AccountUsageUsageTrigger'] = ApiV2010AccountUsageUsageTrigger
from openapi_client.model.inline_response20060 import InlineResponse20060


class TestInlineResponse20060(unittest.TestCase):
    """InlineResponse20060 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20060(self):
        """Test InlineResponse20060"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20060()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
