"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_sip_sip_credential_list import ApiV2010AccountSipSipCredentialList
globals()['ApiV2010AccountSipSipCredentialList'] = ApiV2010AccountSipSipCredentialList
from openapi_client.model.inline_response20038 import InlineResponse20038


class TestInlineResponse20038(unittest.TestCase):
    """InlineResponse20038 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20038(self):
        """Test InlineResponse20038"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20038()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
