"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_account(self):
        """Test case for create_account

        """
        pass

    def test_create_address(self):
        """Test case for create_address

        """
        pass

    def test_create_application(self):
        """Test case for create_application

        """
        pass

    def test_create_call(self):
        """Test case for create_call

        """
        pass

    def test_create_call_feedback_summary(self):
        """Test case for create_call_feedback_summary

        """
        pass

    def test_create_call_recording(self):
        """Test case for create_call_recording

        """
        pass

    def test_create_incoming_phone_number(self):
        """Test case for create_incoming_phone_number

        """
        pass

    def test_create_incoming_phone_number_assigned_add_on(self):
        """Test case for create_incoming_phone_number_assigned_add_on

        """
        pass

    def test_create_incoming_phone_number_local(self):
        """Test case for create_incoming_phone_number_local

        """
        pass

    def test_create_incoming_phone_number_mobile(self):
        """Test case for create_incoming_phone_number_mobile

        """
        pass

    def test_create_incoming_phone_number_toll_free(self):
        """Test case for create_incoming_phone_number_toll_free

        """
        pass

    def test_create_message(self):
        """Test case for create_message

        """
        pass

    def test_create_message_feedback(self):
        """Test case for create_message_feedback

        """
        pass

    def test_create_new_key(self):
        """Test case for create_new_key

        """
        pass

    def test_create_new_signing_key(self):
        """Test case for create_new_signing_key

        """
        pass

    def test_create_participant(self):
        """Test case for create_participant

        """
        pass

    def test_create_payments(self):
        """Test case for create_payments

        """
        pass

    def test_create_queue(self):
        """Test case for create_queue

        """
        pass

    def test_create_sip_auth_calls_credential_list_mapping(self):
        """Test case for create_sip_auth_calls_credential_list_mapping

        """
        pass

    def test_create_sip_auth_calls_ip_access_control_list_mapping(self):
        """Test case for create_sip_auth_calls_ip_access_control_list_mapping

        """
        pass

    def test_create_sip_auth_registrations_credential_list_mapping(self):
        """Test case for create_sip_auth_registrations_credential_list_mapping

        """
        pass

    def test_create_sip_credential(self):
        """Test case for create_sip_credential

        """
        pass

    def test_create_sip_credential_list(self):
        """Test case for create_sip_credential_list

        """
        pass

    def test_create_sip_credential_list_mapping(self):
        """Test case for create_sip_credential_list_mapping

        """
        pass

    def test_create_sip_domain(self):
        """Test case for create_sip_domain

        """
        pass

    def test_create_sip_ip_access_control_list(self):
        """Test case for create_sip_ip_access_control_list

        """
        pass

    def test_create_sip_ip_access_control_list_mapping(self):
        """Test case for create_sip_ip_access_control_list_mapping

        """
        pass

    def test_create_sip_ip_address(self):
        """Test case for create_sip_ip_address

        """
        pass

    def test_create_token(self):
        """Test case for create_token

        """
        pass

    def test_create_usage_trigger(self):
        """Test case for create_usage_trigger

        """
        pass

    def test_create_validation_request(self):
        """Test case for create_validation_request

        """
        pass

    def test_delete_address(self):
        """Test case for delete_address

        """
        pass

    def test_delete_application(self):
        """Test case for delete_application

        """
        pass

    def test_delete_call(self):
        """Test case for delete_call

        """
        pass

    def test_delete_call_feedback_summary(self):
        """Test case for delete_call_feedback_summary

        """
        pass

    def test_delete_call_recording(self):
        """Test case for delete_call_recording

        """
        pass

    def test_delete_conference_recording(self):
        """Test case for delete_conference_recording

        """
        pass

    def test_delete_connect_app(self):
        """Test case for delete_connect_app

        """
        pass

    def test_delete_incoming_phone_number(self):
        """Test case for delete_incoming_phone_number

        """
        pass

    def test_delete_incoming_phone_number_assigned_add_on(self):
        """Test case for delete_incoming_phone_number_assigned_add_on

        """
        pass

    def test_delete_key(self):
        """Test case for delete_key

        """
        pass

    def test_delete_media(self):
        """Test case for delete_media

        """
        pass

    def test_delete_message(self):
        """Test case for delete_message

        """
        pass

    def test_delete_outgoing_caller_id(self):
        """Test case for delete_outgoing_caller_id

        """
        pass

    def test_delete_participant(self):
        """Test case for delete_participant

        """
        pass

    def test_delete_queue(self):
        """Test case for delete_queue

        """
        pass

    def test_delete_recording(self):
        """Test case for delete_recording

        """
        pass

    def test_delete_recording_add_on_result(self):
        """Test case for delete_recording_add_on_result

        """
        pass

    def test_delete_recording_add_on_result_payload(self):
        """Test case for delete_recording_add_on_result_payload

        """
        pass

    def test_delete_recording_transcription(self):
        """Test case for delete_recording_transcription

        """
        pass

    def test_delete_signing_key(self):
        """Test case for delete_signing_key

        """
        pass

    def test_delete_sip_auth_calls_credential_list_mapping(self):
        """Test case for delete_sip_auth_calls_credential_list_mapping

        """
        pass

    def test_delete_sip_auth_calls_ip_access_control_list_mapping(self):
        """Test case for delete_sip_auth_calls_ip_access_control_list_mapping

        """
        pass

    def test_delete_sip_auth_registrations_credential_list_mapping(self):
        """Test case for delete_sip_auth_registrations_credential_list_mapping

        """
        pass

    def test_delete_sip_credential(self):
        """Test case for delete_sip_credential

        """
        pass

    def test_delete_sip_credential_list(self):
        """Test case for delete_sip_credential_list

        """
        pass

    def test_delete_sip_credential_list_mapping(self):
        """Test case for delete_sip_credential_list_mapping

        """
        pass

    def test_delete_sip_domain(self):
        """Test case for delete_sip_domain

        """
        pass

    def test_delete_sip_ip_access_control_list(self):
        """Test case for delete_sip_ip_access_control_list

        """
        pass

    def test_delete_sip_ip_access_control_list_mapping(self):
        """Test case for delete_sip_ip_access_control_list_mapping

        """
        pass

    def test_delete_sip_ip_address(self):
        """Test case for delete_sip_ip_address

        """
        pass

    def test_delete_transcription(self):
        """Test case for delete_transcription

        """
        pass

    def test_delete_usage_trigger(self):
        """Test case for delete_usage_trigger

        """
        pass

    def test_fetch_account(self):
        """Test case for fetch_account

        """
        pass

    def test_fetch_address(self):
        """Test case for fetch_address

        """
        pass

    def test_fetch_application(self):
        """Test case for fetch_application

        """
        pass

    def test_fetch_authorized_connect_app(self):
        """Test case for fetch_authorized_connect_app

        """
        pass

    def test_fetch_available_phone_number_country(self):
        """Test case for fetch_available_phone_number_country

        """
        pass

    def test_fetch_balance(self):
        """Test case for fetch_balance

        """
        pass

    def test_fetch_call(self):
        """Test case for fetch_call

        """
        pass

    def test_fetch_call_feedback(self):
        """Test case for fetch_call_feedback

        """
        pass

    def test_fetch_call_feedback_summary(self):
        """Test case for fetch_call_feedback_summary

        """
        pass

    def test_fetch_call_notification(self):
        """Test case for fetch_call_notification

        """
        pass

    def test_fetch_call_recording(self):
        """Test case for fetch_call_recording

        """
        pass

    def test_fetch_conference(self):
        """Test case for fetch_conference

        """
        pass

    def test_fetch_conference_recording(self):
        """Test case for fetch_conference_recording

        """
        pass

    def test_fetch_connect_app(self):
        """Test case for fetch_connect_app

        """
        pass

    def test_fetch_incoming_phone_number(self):
        """Test case for fetch_incoming_phone_number

        """
        pass

    def test_fetch_incoming_phone_number_assigned_add_on(self):
        """Test case for fetch_incoming_phone_number_assigned_add_on

        """
        pass

    def test_fetch_incoming_phone_number_assigned_add_on_extension(self):
        """Test case for fetch_incoming_phone_number_assigned_add_on_extension

        """
        pass

    def test_fetch_key(self):
        """Test case for fetch_key

        """
        pass

    def test_fetch_media(self):
        """Test case for fetch_media

        """
        pass

    def test_fetch_member(self):
        """Test case for fetch_member

        """
        pass

    def test_fetch_message(self):
        """Test case for fetch_message

        """
        pass

    def test_fetch_notification(self):
        """Test case for fetch_notification

        """
        pass

    def test_fetch_outgoing_caller_id(self):
        """Test case for fetch_outgoing_caller_id

        """
        pass

    def test_fetch_participant(self):
        """Test case for fetch_participant

        """
        pass

    def test_fetch_queue(self):
        """Test case for fetch_queue

        """
        pass

    def test_fetch_recording(self):
        """Test case for fetch_recording

        """
        pass

    def test_fetch_recording_add_on_result(self):
        """Test case for fetch_recording_add_on_result

        """
        pass

    def test_fetch_recording_add_on_result_payload(self):
        """Test case for fetch_recording_add_on_result_payload

        """
        pass

    def test_fetch_recording_transcription(self):
        """Test case for fetch_recording_transcription

        """
        pass

    def test_fetch_short_code(self):
        """Test case for fetch_short_code

        """
        pass

    def test_fetch_signing_key(self):
        """Test case for fetch_signing_key

        """
        pass

    def test_fetch_sip_auth_calls_credential_list_mapping(self):
        """Test case for fetch_sip_auth_calls_credential_list_mapping

        """
        pass

    def test_fetch_sip_auth_calls_ip_access_control_list_mapping(self):
        """Test case for fetch_sip_auth_calls_ip_access_control_list_mapping

        """
        pass

    def test_fetch_sip_auth_registrations_credential_list_mapping(self):
        """Test case for fetch_sip_auth_registrations_credential_list_mapping

        """
        pass

    def test_fetch_sip_credential(self):
        """Test case for fetch_sip_credential

        """
        pass

    def test_fetch_sip_credential_list(self):
        """Test case for fetch_sip_credential_list

        """
        pass

    def test_fetch_sip_credential_list_mapping(self):
        """Test case for fetch_sip_credential_list_mapping

        """
        pass

    def test_fetch_sip_domain(self):
        """Test case for fetch_sip_domain

        """
        pass

    def test_fetch_sip_ip_access_control_list(self):
        """Test case for fetch_sip_ip_access_control_list

        """
        pass

    def test_fetch_sip_ip_access_control_list_mapping(self):
        """Test case for fetch_sip_ip_access_control_list_mapping

        """
        pass

    def test_fetch_sip_ip_address(self):
        """Test case for fetch_sip_ip_address

        """
        pass

    def test_fetch_transcription(self):
        """Test case for fetch_transcription

        """
        pass

    def test_fetch_usage_trigger(self):
        """Test case for fetch_usage_trigger

        """
        pass

    def test_list_account(self):
        """Test case for list_account

        """
        pass

    def test_list_address(self):
        """Test case for list_address

        """
        pass

    def test_list_application(self):
        """Test case for list_application

        """
        pass

    def test_list_authorized_connect_app(self):
        """Test case for list_authorized_connect_app

        """
        pass

    def test_list_available_phone_number_country(self):
        """Test case for list_available_phone_number_country

        """
        pass

    def test_list_available_phone_number_local(self):
        """Test case for list_available_phone_number_local

        """
        pass

    def test_list_available_phone_number_machine_to_machine(self):
        """Test case for list_available_phone_number_machine_to_machine

        """
        pass

    def test_list_available_phone_number_mobile(self):
        """Test case for list_available_phone_number_mobile

        """
        pass

    def test_list_available_phone_number_national(self):
        """Test case for list_available_phone_number_national

        """
        pass

    def test_list_available_phone_number_shared_cost(self):
        """Test case for list_available_phone_number_shared_cost

        """
        pass

    def test_list_available_phone_number_toll_free(self):
        """Test case for list_available_phone_number_toll_free

        """
        pass

    def test_list_available_phone_number_voip(self):
        """Test case for list_available_phone_number_voip

        """
        pass

    def test_list_call(self):
        """Test case for list_call

        """
        pass

    def test_list_call_event(self):
        """Test case for list_call_event

        """
        pass

    def test_list_call_notification(self):
        """Test case for list_call_notification

        """
        pass

    def test_list_call_recording(self):
        """Test case for list_call_recording

        """
        pass

    def test_list_conference(self):
        """Test case for list_conference

        """
        pass

    def test_list_conference_recording(self):
        """Test case for list_conference_recording

        """
        pass

    def test_list_connect_app(self):
        """Test case for list_connect_app

        """
        pass

    def test_list_dependent_phone_number(self):
        """Test case for list_dependent_phone_number

        """
        pass

    def test_list_incoming_phone_number(self):
        """Test case for list_incoming_phone_number

        """
        pass

    def test_list_incoming_phone_number_assigned_add_on(self):
        """Test case for list_incoming_phone_number_assigned_add_on

        """
        pass

    def test_list_incoming_phone_number_assigned_add_on_extension(self):
        """Test case for list_incoming_phone_number_assigned_add_on_extension

        """
        pass

    def test_list_incoming_phone_number_local(self):
        """Test case for list_incoming_phone_number_local

        """
        pass

    def test_list_incoming_phone_number_mobile(self):
        """Test case for list_incoming_phone_number_mobile

        """
        pass

    def test_list_incoming_phone_number_toll_free(self):
        """Test case for list_incoming_phone_number_toll_free

        """
        pass

    def test_list_key(self):
        """Test case for list_key

        """
        pass

    def test_list_media(self):
        """Test case for list_media

        """
        pass

    def test_list_member(self):
        """Test case for list_member

        """
        pass

    def test_list_message(self):
        """Test case for list_message

        """
        pass

    def test_list_notification(self):
        """Test case for list_notification

        """
        pass

    def test_list_outgoing_caller_id(self):
        """Test case for list_outgoing_caller_id

        """
        pass

    def test_list_participant(self):
        """Test case for list_participant

        """
        pass

    def test_list_queue(self):
        """Test case for list_queue

        """
        pass

    def test_list_recording(self):
        """Test case for list_recording

        """
        pass

    def test_list_recording_add_on_result(self):
        """Test case for list_recording_add_on_result

        """
        pass

    def test_list_recording_add_on_result_payload(self):
        """Test case for list_recording_add_on_result_payload

        """
        pass

    def test_list_recording_transcription(self):
        """Test case for list_recording_transcription

        """
        pass

    def test_list_short_code(self):
        """Test case for list_short_code

        """
        pass

    def test_list_signing_key(self):
        """Test case for list_signing_key

        """
        pass

    def test_list_sip_auth_calls_credential_list_mapping(self):
        """Test case for list_sip_auth_calls_credential_list_mapping

        """
        pass

    def test_list_sip_auth_calls_ip_access_control_list_mapping(self):
        """Test case for list_sip_auth_calls_ip_access_control_list_mapping

        """
        pass

    def test_list_sip_auth_registrations_credential_list_mapping(self):
        """Test case for list_sip_auth_registrations_credential_list_mapping

        """
        pass

    def test_list_sip_credential(self):
        """Test case for list_sip_credential

        """
        pass

    def test_list_sip_credential_list(self):
        """Test case for list_sip_credential_list

        """
        pass

    def test_list_sip_credential_list_mapping(self):
        """Test case for list_sip_credential_list_mapping

        """
        pass

    def test_list_sip_domain(self):
        """Test case for list_sip_domain

        """
        pass

    def test_list_sip_ip_access_control_list(self):
        """Test case for list_sip_ip_access_control_list

        """
        pass

    def test_list_sip_ip_access_control_list_mapping(self):
        """Test case for list_sip_ip_access_control_list_mapping

        """
        pass

    def test_list_sip_ip_address(self):
        """Test case for list_sip_ip_address

        """
        pass

    def test_list_transcription(self):
        """Test case for list_transcription

        """
        pass

    def test_list_usage_record(self):
        """Test case for list_usage_record

        """
        pass

    def test_list_usage_record_all_time(self):
        """Test case for list_usage_record_all_time

        """
        pass

    def test_list_usage_record_daily(self):
        """Test case for list_usage_record_daily

        """
        pass

    def test_list_usage_record_last_month(self):
        """Test case for list_usage_record_last_month

        """
        pass

    def test_list_usage_record_monthly(self):
        """Test case for list_usage_record_monthly

        """
        pass

    def test_list_usage_record_this_month(self):
        """Test case for list_usage_record_this_month

        """
        pass

    def test_list_usage_record_today(self):
        """Test case for list_usage_record_today

        """
        pass

    def test_list_usage_record_yearly(self):
        """Test case for list_usage_record_yearly

        """
        pass

    def test_list_usage_record_yesterday(self):
        """Test case for list_usage_record_yesterday

        """
        pass

    def test_list_usage_trigger(self):
        """Test case for list_usage_trigger

        """
        pass

    def test_update_account(self):
        """Test case for update_account

        """
        pass

    def test_update_address(self):
        """Test case for update_address

        """
        pass

    def test_update_application(self):
        """Test case for update_application

        """
        pass

    def test_update_call(self):
        """Test case for update_call

        """
        pass

    def test_update_call_feedback(self):
        """Test case for update_call_feedback

        """
        pass

    def test_update_call_recording(self):
        """Test case for update_call_recording

        """
        pass

    def test_update_conference(self):
        """Test case for update_conference

        """
        pass

    def test_update_conference_recording(self):
        """Test case for update_conference_recording

        """
        pass

    def test_update_connect_app(self):
        """Test case for update_connect_app

        """
        pass

    def test_update_incoming_phone_number(self):
        """Test case for update_incoming_phone_number

        """
        pass

    def test_update_key(self):
        """Test case for update_key

        """
        pass

    def test_update_member(self):
        """Test case for update_member

        """
        pass

    def test_update_message(self):
        """Test case for update_message

        """
        pass

    def test_update_outgoing_caller_id(self):
        """Test case for update_outgoing_caller_id

        """
        pass

    def test_update_participant(self):
        """Test case for update_participant

        """
        pass

    def test_update_payments(self):
        """Test case for update_payments

        """
        pass

    def test_update_queue(self):
        """Test case for update_queue

        """
        pass

    def test_update_short_code(self):
        """Test case for update_short_code

        """
        pass

    def test_update_signing_key(self):
        """Test case for update_signing_key

        """
        pass

    def test_update_sip_credential(self):
        """Test case for update_sip_credential

        """
        pass

    def test_update_sip_credential_list(self):
        """Test case for update_sip_credential_list

        """
        pass

    def test_update_sip_domain(self):
        """Test case for update_sip_domain

        """
        pass

    def test_update_sip_ip_access_control_list(self):
        """Test case for update_sip_ip_access_control_list

        """
        pass

    def test_update_sip_ip_address(self):
        """Test case for update_sip_ip_address

        """
        pass

    def test_update_usage_trigger(self):
        """Test case for update_usage_trigger

        """
        pass


if __name__ == '__main__':
    unittest.main()
