"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_sip_sip_domain_sip_credential_list_mapping import ApiV2010AccountSipSipDomainSipCredentialListMapping
globals()['ApiV2010AccountSipSipDomainSipCredentialListMapping'] = ApiV2010AccountSipSipDomainSipCredentialListMapping
from openapi_client.model.inline_response20044 import InlineResponse20044


class TestInlineResponse20044(unittest.TestCase):
    """InlineResponse20044 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20044(self):
        """Test InlineResponse20044"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20044()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
