"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_sip_sip_domain_sip_ip_access_control_list_mapping import ApiV2010AccountSipSipDomainSipIpAccessControlListMapping
globals()['ApiV2010AccountSipSipDomainSipIpAccessControlListMapping'] = ApiV2010AccountSipSipDomainSipIpAccessControlListMapping
from openapi_client.model.inline_response20045 import InlineResponse20045


class TestInlineResponse20045(unittest.TestCase):
    """InlineResponse20045 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20045(self):
        """Test InlineResponse20045"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20045()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
