"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_available_phone_number_country_available_phone_number_toll_free import ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberTollFree


class TestApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberTollFree(unittest.TestCase):
    """ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberTollFree unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberTollFree(self):
        """Test ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberTollFree"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberTollFree()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
