"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_conference import ApiV2010AccountConference
globals()['ApiV2010AccountConference'] = ApiV2010AccountConference
from openapi_client.model.inline_response20017 import InlineResponse20017


class TestInlineResponse20017(unittest.TestCase):
    """InlineResponse20017 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20017(self):
        """Test InlineResponse20017"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20017()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
