"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record_usage_record_yearly import ApiV2010AccountUsageUsageRecordUsageRecordYearly
globals()['ApiV2010AccountUsageUsageRecordUsageRecordYearly'] = ApiV2010AccountUsageUsageRecordUsageRecordYearly
from openapi_client.model.inline_response20058 import InlineResponse20058


class TestInlineResponse20058(unittest.TestCase):
    """InlineResponse20058 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20058(self):
        """Test InlineResponse20058"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20058()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
