"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_key import ApiV2010AccountKey
globals()['ApiV2010AccountKey'] = ApiV2010AccountKey
from openapi_client.model.inline_response20027 import InlineResponse20027


class TestInlineResponse20027(unittest.TestCase):
    """InlineResponse20027 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20027(self):
        """Test InlineResponse20027"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20027()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
