"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_connect_app import ApiV2010AccountConnectApp
globals()['ApiV2010AccountConnectApp'] = ApiV2010AccountConnectApp
from openapi_client.model.inline_response20020 import InlineResponse20020


class TestInlineResponse20020(unittest.TestCase):
    """InlineResponse20020 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20020(self):
        """Test InlineResponse20020"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20020()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
