"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_sip_sip_ip_access_control_list import ApiV2010AccountSipSipIpAccessControlList
globals()['ApiV2010AccountSipSipIpAccessControlList'] = ApiV2010AccountSipSipIpAccessControlList
from openapi_client.model.inline_response20046 import InlineResponse20046


class TestInlineResponse20046(unittest.TestCase):
    """InlineResponse20046 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20046(self):
        """Test InlineResponse20046"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20046()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
