"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record import ApiV2010AccountUsageUsageRecord
globals()['ApiV2010AccountUsageUsageRecord'] = ApiV2010AccountUsageUsageRecord
from openapi_client.model.inline_response20051 import InlineResponse20051


class TestInlineResponse20051(unittest.TestCase):
    """InlineResponse20051 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20051(self):
        """Test InlineResponse20051"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20051()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
