"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record_usage_record_monthly import ApiV2010AccountUsageUsageRecordUsageRecordMonthly
globals()['ApiV2010AccountUsageUsageRecordUsageRecordMonthly'] = ApiV2010AccountUsageUsageRecordUsageRecordMonthly
from openapi_client.model.inline_response20055 import InlineResponse20055


class TestInlineResponse20055(unittest.TestCase):
    """InlineResponse20055 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20055(self):
        """Test InlineResponse20055"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20055()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
