"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record_usage_record_all_time import ApiV2010AccountUsageUsageRecordUsageRecordAllTime
globals()['ApiV2010AccountUsageUsageRecordUsageRecordAllTime'] = ApiV2010AccountUsageUsageRecordUsageRecordAllTime
from openapi_client.model.inline_response20052 import InlineResponse20052


class TestInlineResponse20052(unittest.TestCase):
    """InlineResponse20052 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20052(self):
        """Test InlineResponse20052"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20052()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
