"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record_usage_record_yesterday import ApiV2010AccountUsageUsageRecordUsageRecordYesterday
globals()['ApiV2010AccountUsageUsageRecordUsageRecordYesterday'] = ApiV2010AccountUsageUsageRecordUsageRecordYesterday
from openapi_client.model.inline_response20059 import InlineResponse20059


class TestInlineResponse20059(unittest.TestCase):
    """InlineResponse20059 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20059(self):
        """Test InlineResponse20059"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20059()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
