"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_message_media import ApiV2010AccountMessageMedia
globals()['ApiV2010AccountMessageMedia'] = ApiV2010AccountMessageMedia
from openapi_client.model.inline_response20029 import InlineResponse20029


class TestInlineResponse20029(unittest.TestCase):
    """InlineResponse20029 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20029(self):
        """Test InlineResponse20029"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20029()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
