"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_validation_request import ApiV2010AccountValidationRequest


class TestApiV2010AccountValidationRequest(unittest.TestCase):
    """ApiV2010AccountValidationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV2010AccountValidationRequest(self):
        """Test ApiV2010AccountValidationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV2010AccountValidationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
