"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_conference_participant import ApiV2010AccountConferenceParticipant
globals()['ApiV2010AccountConferenceParticipant'] = ApiV2010AccountConferenceParticipant
from openapi_client.model.inline_response20018 import InlineResponse20018


class TestInlineResponse20018(unittest.TestCase):
    """InlineResponse20018 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20018(self):
        """Test InlineResponse20018"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20018()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
