"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record_usage_record_today import ApiV2010AccountUsageUsageRecordUsageRecordToday
globals()['ApiV2010AccountUsageUsageRecordUsageRecordToday'] = ApiV2010AccountUsageUsageRecordUsageRecordToday
from openapi_client.model.inline_response20057 import InlineResponse20057


class TestInlineResponse20057(unittest.TestCase):
    """InlineResponse20057 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20057(self):
        """Test InlineResponse20057"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20057()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
