"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_conference_conference_recording import ApiV2010AccountConferenceConferenceRecording
globals()['ApiV2010AccountConferenceConferenceRecording'] = ApiV2010AccountConferenceConferenceRecording
from openapi_client.model.inline_response20019 import InlineResponse20019


class TestInlineResponse20019(unittest.TestCase):
    """InlineResponse20019 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20019(self):
        """Test InlineResponse20019"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20019()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
