"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record_usage_record_this_month import ApiV2010AccountUsageUsageRecordUsageRecordThisMonth


class TestApiV2010AccountUsageUsageRecordUsageRecordThisMonth(unittest.TestCase):
    """ApiV2010AccountUsageUsageRecordUsageRecordThisMonth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV2010AccountUsageUsageRecordUsageRecordThisMonth(self):
        """Test ApiV2010AccountUsageUsageRecordUsageRecordThisMonth"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV2010AccountUsageUsageRecordUsageRecordThisMonth()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
