"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_available_phone_number_country_available_phone_number_mobile import ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberMobile
globals()['ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberMobile'] = ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberMobile
from openapi_client.model.inline_response2008 import InlineResponse2008


class TestInlineResponse2008(unittest.TestCase):
    """InlineResponse2008 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2008(self):
        """Test InlineResponse2008"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2008()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
