"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_notification import ApiV2010AccountNotification
globals()['ApiV2010AccountNotification'] = ApiV2010AccountNotification
from openapi_client.model.inline_response20030 import InlineResponse20030


class TestInlineResponse20030(unittest.TestCase):
    """InlineResponse20030 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20030(self):
        """Test InlineResponse20030"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20030()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
