"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_usage_usage_record_usage_record_last_month import ApiV2010AccountUsageUsageRecordUsageRecordLastMonth
globals()['ApiV2010AccountUsageUsageRecordUsageRecordLastMonth'] = ApiV2010AccountUsageUsageRecordUsageRecordLastMonth
from openapi_client.model.inline_response20054 import InlineResponse20054


class TestInlineResponse20054(unittest.TestCase):
    """InlineResponse20054 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20054(self):
        """Test InlineResponse20054"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20054()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
