"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_message_media import ApiV2010AccountMessageMedia


class TestApiV2010AccountMessageMedia(unittest.TestCase):
    """ApiV2010AccountMessageMedia unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV2010AccountMessageMedia(self):
        """Test ApiV2010AccountMessageMedia"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV2010AccountMessageMedia()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
