"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.api_v2010_account_available_phone_number_country_available_phone_number_national import ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberNational


class TestApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberNational(unittest.TestCase):
    """ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberNational unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberNational(self):
        """Test ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberNational"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiV2010AccountAvailablePhoneNumberCountryAvailablePhoneNumberNational()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
