"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

import nulltype  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class ApiV2010AccountUsageUsageRecordUsageRecordYearly(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('category',): {
            'AGENT-CONFERENCE': "agent-conference",
            'ANSWERING-MACHINE-DETECTION': "answering-machine-detection",
            'AUTHY-AUTHENTICATIONS': "authy-authentications",
            'AUTHY-CALLS-OUTBOUND': "authy-calls-outbound",
            'AUTHY-MONTHLY-FEES': "authy-monthly-fees",
            'AUTHY-PHONE-INTELLIGENCE': "authy-phone-intelligence",
            'AUTHY-PHONE-VERIFICATIONS': "authy-phone-verifications",
            'AUTHY-SMS-OUTBOUND': "authy-sms-outbound",
            'CALL-PROGESS-EVENTS': "call-progess-events",
            'CALLERIDLOOKUPS': "calleridlookups",
            'CALLS': "calls",
            'CALLS-CLIENT': "calls-client",
            'CALLS-GLOBALCONFERENCE': "calls-globalconference",
            'CALLS-INBOUND': "calls-inbound",
            'CALLS-INBOUND-LOCAL': "calls-inbound-local",
            'CALLS-INBOUND-MOBILE': "calls-inbound-mobile",
            'CALLS-INBOUND-TOLLFREE': "calls-inbound-tollfree",
            'CALLS-OUTBOUND': "calls-outbound",
            'CALLS-PAY-VERB-TRANSACTIONS': "calls-pay-verb-transactions",
            'CALLS-RECORDINGS': "calls-recordings",
            'CALLS-SIP': "calls-sip",
            'CALLS-SIP-INBOUND': "calls-sip-inbound",
            'CALLS-SIP-OUTBOUND': "calls-sip-outbound",
            'CARRIER-LOOKUPS': "carrier-lookups",
            'CONVERSATIONS': "conversations",
            'CONVERSATIONS-API-REQUESTS': "conversations-api-requests",
            'CONVERSATIONS-CONVERSATION-EVENTS': "conversations-conversation-events",
            'CONVERSATIONS-ENDPOINT-CONNECTIVITY': "conversations-endpoint-connectivity",
            'CONVERSATIONS-EVENTS': "conversations-events",
            'CONVERSATIONS-PARTICIPANT-EVENTS': "conversations-participant-events",
            'CONVERSATIONS-PARTICIPANTS': "conversations-participants",
            'CPS': "cps",
            'FRAUD-LOOKUPS': "fraud-lookups",
            'GROUP-ROOMS': "group-rooms",
            'GROUP-ROOMS-DATA-TRACK': "group-rooms-data-track",
            'GROUP-ROOMS-ENCRYPTED-MEDIA-RECORDED': "group-rooms-encrypted-media-recorded",
            'GROUP-ROOMS-MEDIA-DOWNLOADED': "group-rooms-media-downloaded",
            'GROUP-ROOMS-MEDIA-RECORDED': "group-rooms-media-recorded",
            'GROUP-ROOMS-MEDIA-ROUTED': "group-rooms-media-routed",
            'GROUP-ROOMS-MEDIA-STORED': "group-rooms-media-stored",
            'GROUP-ROOMS-PARTICIPANT-MINUTES': "group-rooms-participant-minutes",
            'GROUP-ROOMS-RECORDED-MINUTES': "group-rooms-recorded-minutes",
            'IMP-V1-USAGE': "imp-v1-usage",
            'LOOKUPS': "lookups",
            'MARKETPLACE': "marketplace",
            'MARKETPLACE-ALGORITHMIA-NAMED-ENTITY-RECOGNITION': "marketplace-algorithmia-named-entity-recognition",
            'MARKETPLACE-CADENCE-TRANSCRIPTION': "marketplace-cadence-transcription",
            'MARKETPLACE-CADENCE-TRANSLATION': "marketplace-cadence-translation",
            'MARKETPLACE-CAPIO-SPEECH-TO-TEXT': "marketplace-capio-speech-to-text",
            'MARKETPLACE-CONVRIZA-ABABA': "marketplace-convriza-ababa",
            'MARKETPLACE-DEEPGRAM-PHRASE-DETECTOR': "marketplace-deepgram-phrase-detector",
            'MARKETPLACE-DIGITAL-SEGMENT-BUSINESS-INFO': "marketplace-digital-segment-business-info",
            'MARKETPLACE-FACEBOOK-OFFLINE-CONVERSIONS': "marketplace-facebook-offline-conversions",
            'MARKETPLACE-GOOGLE-SPEECH-TO-TEXT': "marketplace-google-speech-to-text",
            'MARKETPLACE-IBM-WATSON-MESSAGE-INSIGHTS': "marketplace-ibm-watson-message-insights",
            'MARKETPLACE-IBM-WATSON-MESSAGE-SENTIMENT': "marketplace-ibm-watson-message-sentiment",
            'MARKETPLACE-IBM-WATSON-RECORDING-ANALYSIS': "marketplace-ibm-watson-recording-analysis",
            'MARKETPLACE-IBM-WATSON-TONE-ANALYZER': "marketplace-ibm-watson-tone-analyzer",
            'MARKETPLACE-ICEHOOK-SYSTEMS-SCOUT': "marketplace-icehook-systems-scout",
            'MARKETPLACE-INFOGROUP-DATAAXLE-BIZINFO': "marketplace-infogroup-dataaxle-bizinfo",
            'MARKETPLACE-KEEN-IO-CONTACT-CENTER-ANALYTICS': "marketplace-keen-io-contact-center-analytics",
            'MARKETPLACE-MARCHEX-CLEANCALL': "marketplace-marchex-cleancall",
            'MARKETPLACE-MARCHEX-SENTIMENT-ANALYSIS-FOR-SMS': "marketplace-marchex-sentiment-analysis-for-sms",
            'MARKETPLACE-MARKETPLACE-NEXTCALLER-SOCIAL-ID': "marketplace-marketplace-nextcaller-social-id",
            'MARKETPLACE-MOBILE-COMMONS-OPT-OUT-CLASSIFIER': "marketplace-mobile-commons-opt-out-classifier",
            'MARKETPLACE-NEXIWAVE-VOICEMAIL-TO-TEXT': "marketplace-nexiwave-voicemail-to-text",
            'MARKETPLACE-NEXTCALLER-ADVANCED-CALLER-IDENTIFICATION': "marketplace-nextcaller-advanced-caller-identification",
            'MARKETPLACE-NOMOROBO-SPAM-SCORE': "marketplace-nomorobo-spam-score",
            'MARKETPLACE-PAYFONE-TCPA-COMPLIANCE': "marketplace-payfone-tcpa-compliance",
            'MARKETPLACE-REMEETING-AUTOMATIC-SPEECH-RECOGNITION': "marketplace-remeeting-automatic-speech-recognition",
            'MARKETPLACE-TCPA-DEFENSE-SOLUTIONS-BLACKLIST-FEED': "marketplace-tcpa-defense-solutions-blacklist-feed",
            'MARKETPLACE-TELO-OPENCNAM': "marketplace-telo-opencnam",
            'MARKETPLACE-TRUECNAM-TRUE-SPAM': "marketplace-truecnam-true-spam",
            'MARKETPLACE-TWILIO-CALLER-NAME-LOOKUP-US': "marketplace-twilio-caller-name-lookup-us",
            'MARKETPLACE-TWILIO-CARRIER-INFORMATION-LOOKUP': "marketplace-twilio-carrier-information-lookup",
            'MARKETPLACE-VOICEBASE-PCI': "marketplace-voicebase-pci",
            'MARKETPLACE-VOICEBASE-TRANSCRIPTION': "marketplace-voicebase-transcription",
            'MARKETPLACE-VOICEBASE-TRANSCRIPTION-CUSTOM-VOCABULARY': "marketplace-voicebase-transcription-custom-vocabulary",
            'MARKETPLACE-WHITEPAGES-PRO-CALLER-IDENTIFICATION': "marketplace-whitepages-pro-caller-identification",
            'MARKETPLACE-WHITEPAGES-PRO-PHONE-INTELLIGENCE': "marketplace-whitepages-pro-phone-intelligence",
            'MARKETPLACE-WHITEPAGES-PRO-PHONE-REPUTATION': "marketplace-whitepages-pro-phone-reputation",
            'MARKETPLACE-WOLFARM-SPOKEN-RESULTS': "marketplace-wolfarm-spoken-results",
            'MARKETPLACE-WOLFRAM-SHORT-ANSWER': "marketplace-wolfram-short-answer",
            'MARKETPLACE-YTICA-CONTACT-CENTER-REPORTING-ANALYTICS': "marketplace-ytica-contact-center-reporting-analytics",
            'MEDIASTORAGE': "mediastorage",
            'MMS': "mms",
            'MMS-INBOUND': "mms-inbound",
            'MMS-INBOUND-LONGCODE': "mms-inbound-longcode",
            'MMS-INBOUND-SHORTCODE': "mms-inbound-shortcode",
            'MMS-MESSAGES-CARRIERFEES': "mms-messages-carrierfees",
            'MMS-OUTBOUND': "mms-outbound",
            'MMS-OUTBOUND-LONGCODE': "mms-outbound-longcode",
            'MMS-OUTBOUND-SHORTCODE': "mms-outbound-shortcode",
            'MONITOR-READS': "monitor-reads",
            'MONITOR-STORAGE': "monitor-storage",
            'MONITOR-WRITES': "monitor-writes",
            'NOTIFY': "notify",
            'NOTIFY-ACTIONS-ATTEMPTS': "notify-actions-attempts",
            'NOTIFY-CHANNELS': "notify-channels",
            'NUMBER-FORMAT-LOOKUPS': "number-format-lookups",
            'PCHAT': "pchat",
            'PCHAT-USERS': "pchat-users",
            'PEER-TO-PEER-ROOMS-PARTICIPANT-MINUTES': "peer-to-peer-rooms-participant-minutes",
            'PFAX': "pfax",
            'PFAX-MINUTES': "pfax-minutes",
            'PFAX-MINUTES-INBOUND': "pfax-minutes-inbound",
            'PFAX-MINUTES-OUTBOUND': "pfax-minutes-outbound",
            'PFAX-PAGES': "pfax-pages",
            'PHONENUMBERS': "phonenumbers",
            'PHONENUMBERS-CPS': "phonenumbers-cps",
            'PHONENUMBERS-EMERGENCY': "phonenumbers-emergency",
            'PHONENUMBERS-LOCAL': "phonenumbers-local",
            'PHONENUMBERS-MOBILE': "phonenumbers-mobile",
            'PHONENUMBERS-SETUPS': "phonenumbers-setups",
            'PHONENUMBERS-TOLLFREE': "phonenumbers-tollfree",
            'PREMIUMSUPPORT': "premiumsupport",
            'PROXY': "proxy",
            'PROXY-ACTIVE-SESSIONS': "proxy-active-sessions",
            'PSTNCONNECTIVITY': "pstnconnectivity",
            'PV': "pv",
            'PV-COMPOSITION-MEDIA-DOWNLOADED': "pv-composition-media-downloaded",
            'PV-COMPOSITION-MEDIA-ENCRYPTED': "pv-composition-media-encrypted",
            'PV-COMPOSITION-MEDIA-STORED': "pv-composition-media-stored",
            'PV-COMPOSITION-MINUTES': "pv-composition-minutes",
            'PV-RECORDING-COMPOSITIONS': "pv-recording-compositions",
            'PV-ROOM-PARTICIPANTS': "pv-room-participants",
            'PV-ROOM-PARTICIPANTS-AU1': "pv-room-participants-au1",
            'PV-ROOM-PARTICIPANTS-BR1': "pv-room-participants-br1",
            'PV-ROOM-PARTICIPANTS-IE1': "pv-room-participants-ie1",
            'PV-ROOM-PARTICIPANTS-JP1': "pv-room-participants-jp1",
            'PV-ROOM-PARTICIPANTS-SG1': "pv-room-participants-sg1",
            'PV-ROOM-PARTICIPANTS-US1': "pv-room-participants-us1",
            'PV-ROOM-PARTICIPANTS-US2': "pv-room-participants-us2",
            'PV-ROOMS': "pv-rooms",
            'PV-SIP-ENDPOINT-REGISTRATIONS': "pv-sip-endpoint-registrations",
            'RECORDINGS': "recordings",
            'RECORDINGSTORAGE': "recordingstorage",
            'ROOMS-GROUP-BANDWIDTH': "rooms-group-bandwidth",
            'ROOMS-GROUP-MINUTES': "rooms-group-minutes",
            'ROOMS-PEER-TO-PEER-MINUTES': "rooms-peer-to-peer-minutes",
            'SHORTCODES': "shortcodes",
            'SHORTCODES-CUSTOMEROWNED': "shortcodes-customerowned",
            'SHORTCODES-MMS-ENABLEMENT': "shortcodes-mms-enablement",
            'SHORTCODES-MPS': "shortcodes-mps",
            'SHORTCODES-RANDOM': "shortcodes-random",
            'SHORTCODES-UK': "shortcodes-uk",
            'SHORTCODES-VANITY': "shortcodes-vanity",
            'SMALL-GROUP-ROOMS': "small-group-rooms",
            'SMALL-GROUP-ROOMS-DATA-TRACK': "small-group-rooms-data-track",
            'SMALL-GROUP-ROOMS-PARTICIPANT-MINUTES': "small-group-rooms-participant-minutes",
            'SMS': "sms",
            'SMS-INBOUND': "sms-inbound",
            'SMS-INBOUND-LONGCODE': "sms-inbound-longcode",
            'SMS-INBOUND-SHORTCODE': "sms-inbound-shortcode",
            'SMS-MESSAGES-CARRIERFEES': "sms-messages-carrierfees",
            'SMS-MESSAGES-FEATURES': "sms-messages-features",
            'SMS-MESSAGES-FEATURES-SENDERID': "sms-messages-features-senderid",
            'SMS-OUTBOUND': "sms-outbound",
            'SMS-OUTBOUND-CONTENT-INSPECTION': "sms-outbound-content-inspection",
            'SMS-OUTBOUND-LONGCODE': "sms-outbound-longcode",
            'SMS-OUTBOUND-SHORTCODE': "sms-outbound-shortcode",
            'SPEECH-RECOGNITION': "speech-recognition",
            'STUDIO-ENGAGEMENTS': "studio-engagements",
            'SYNC': "sync",
            'SYNC-ACTIONS': "sync-actions",
            'SYNC-ENDPOINT-HOURS': "sync-endpoint-hours",
            'SYNC-ENDPOINT-HOURS-ABOVE-DAILY-CAP': "sync-endpoint-hours-above-daily-cap",
            'TASKROUTER-TASKS': "taskrouter-tasks",
            'TOTALPRICE': "totalprice",
            'TRANSCRIPTIONS': "transcriptions",
            'TRUNKING-CPS': "trunking-cps",
            'TRUNKING-EMERGENCY-CALLS': "trunking-emergency-calls",
            'TRUNKING-ORIGINATION': "trunking-origination",
            'TRUNKING-ORIGINATION-LOCAL': "trunking-origination-local",
            'TRUNKING-ORIGINATION-MOBILE': "trunking-origination-mobile",
            'TRUNKING-ORIGINATION-TOLLFREE': "trunking-origination-tollfree",
            'TRUNKING-RECORDINGS': "trunking-recordings",
            'TRUNKING-SECURE': "trunking-secure",
            'TRUNKING-TERMINATION': "trunking-termination",
            'TURNMEGABYTES': "turnmegabytes",
            'TURNMEGABYTES-AUSTRALIA': "turnmegabytes-australia",
            'TURNMEGABYTES-BRASIL': "turnmegabytes-brasil",
            'TURNMEGABYTES-GERMANY': "turnmegabytes-germany",
            'TURNMEGABYTES-INDIA': "turnmegabytes-india",
            'TURNMEGABYTES-IRELAND': "turnmegabytes-ireland",
            'TURNMEGABYTES-JAPAN': "turnmegabytes-japan",
            'TURNMEGABYTES-SINGAPORE': "turnmegabytes-singapore",
            'TURNMEGABYTES-USEAST': "turnmegabytes-useast",
            'TURNMEGABYTES-USWEST': "turnmegabytes-uswest",
            'TWILIO-INTERCONNECT': "twilio-interconnect",
            'VERIFY-PUSH': "verify-push",
            'VIDEO-RECORDINGS': "video-recordings",
            'VOICE-INSIGHTS': "voice-insights",
            'VOICE-INSIGHTS-CLIENT-INSIGHTS-ON-DEMAND-MINUTE': "voice-insights-client-insights-on-demand-minute",
            'VOICE-INSIGHTS-PTSN-INSIGHTS-ON-DEMAND-MINUTE': "voice-insights-ptsn-insights-on-demand-minute",
            'VOICE-INSIGHTS-SIP-INTERFACE-INSIGHTS-ON-DEMAND-MINUTE': "voice-insights-sip-interface-insights-on-demand-minute",
            'VOICE-INSIGHTS-SIP-TRUNKING-INSIGHTS-ON-DEMAND-MINUTE': "voice-insights-sip-trunking-insights-on-demand-minute",
            'WIRELESS': "wireless",
            'WIRELESS-ORDERS': "wireless-orders",
            'WIRELESS-ORDERS-ARTWORK': "wireless-orders-artwork",
            'WIRELESS-ORDERS-BULK': "wireless-orders-bulk",
            'WIRELESS-ORDERS-ESIM': "wireless-orders-esim",
            'WIRELESS-ORDERS-STARTER': "wireless-orders-starter",
            'WIRELESS-USAGE': "wireless-usage",
            'WIRELESS-USAGE-COMMANDS': "wireless-usage-commands",
            'WIRELESS-USAGE-COMMANDS-AFRICA': "wireless-usage-commands-africa",
            'WIRELESS-USAGE-COMMANDS-ASIA': "wireless-usage-commands-asia",
            'WIRELESS-USAGE-COMMANDS-CENTRALANDSOUTHAMERICA': "wireless-usage-commands-centralandsouthamerica",
            'WIRELESS-USAGE-COMMANDS-EUROPE': "wireless-usage-commands-europe",
            'WIRELESS-USAGE-COMMANDS-HOME': "wireless-usage-commands-home",
            'WIRELESS-USAGE-COMMANDS-NORTHAMERICA': "wireless-usage-commands-northamerica",
            'WIRELESS-USAGE-COMMANDS-OCEANIA': "wireless-usage-commands-oceania",
            'WIRELESS-USAGE-COMMANDS-ROAMING': "wireless-usage-commands-roaming",
            'WIRELESS-USAGE-DATA': "wireless-usage-data",
            'WIRELESS-USAGE-DATA-AFRICA': "wireless-usage-data-africa",
            'WIRELESS-USAGE-DATA-ASIA': "wireless-usage-data-asia",
            'WIRELESS-USAGE-DATA-CENTRALANDSOUTHAMERICA': "wireless-usage-data-centralandsouthamerica",
            'WIRELESS-USAGE-DATA-CUSTOM-ADDITIONALMB': "wireless-usage-data-custom-additionalmb",
            'WIRELESS-USAGE-DATA-CUSTOM-FIRST5MB': "wireless-usage-data-custom-first5mb",
            'WIRELESS-USAGE-DATA-DOMESTIC-ROAMING': "wireless-usage-data-domestic-roaming",
            'WIRELESS-USAGE-DATA-EUROPE': "wireless-usage-data-europe",
            'WIRELESS-USAGE-DATA-INDIVIDUAL-ADDITIONALGB': "wireless-usage-data-individual-additionalgb",
            'WIRELESS-USAGE-DATA-INDIVIDUAL-FIRSTGB': "wireless-usage-data-individual-firstgb",
            'WIRELESS-USAGE-DATA-INTERNATIONAL-ROAMING-CANADA': "wireless-usage-data-international-roaming-canada",
            'WIRELESS-USAGE-DATA-INTERNATIONAL-ROAMING-INDIA': "wireless-usage-data-international-roaming-india",
            'WIRELESS-USAGE-DATA-INTERNATIONAL-ROAMING-MEXICO': "wireless-usage-data-international-roaming-mexico",
            'WIRELESS-USAGE-DATA-NORTHAMERICA': "wireless-usage-data-northamerica",
            'WIRELESS-USAGE-DATA-OCEANIA': "wireless-usage-data-oceania",
            'WIRELESS-USAGE-DATA-POOLED': "wireless-usage-data-pooled",
            'WIRELESS-USAGE-DATA-POOLED-DOWNLINK': "wireless-usage-data-pooled-downlink",
            'WIRELESS-USAGE-DATA-POOLED-UPLINK': "wireless-usage-data-pooled-uplink",
            'WIRELESS-USAGE-MRC': "wireless-usage-mrc",
            'WIRELESS-USAGE-MRC-CUSTOM': "wireless-usage-mrc-custom",
            'WIRELESS-USAGE-MRC-INDIVIDUAL': "wireless-usage-mrc-individual",
            'WIRELESS-USAGE-MRC-POOLED': "wireless-usage-mrc-pooled",
            'WIRELESS-USAGE-MRC-SUSPENDED': "wireless-usage-mrc-suspended",
            'WIRELESS-USAGE-SMS': "wireless-usage-sms",
            'WIRELESS-USAGE-VOICE': "wireless-usage-voice",
        },
    }

    validations = {
        ('account_sid',): {
            'max_length': 34,
            'min_length': 34,
            'regex': {
                'pattern': r'^AC[0-9a-fA-F]{32}$',  # noqa: E501
            },
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'account_sid': (str,),  # noqa: E501
            'api_version': (str,),  # noqa: E501
            'as_of': (str,),  # noqa: E501
            'category': (str,),  # noqa: E501
            'count': (str,),  # noqa: E501
            'count_unit': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'end_date': (datetime,),  # noqa: E501
            'price': (float,),  # noqa: E501
            'price_unit': (str,),  # noqa: E501
            'start_date': (datetime,),  # noqa: E501
            'subresource_uris': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'uri': (str,),  # noqa: E501
            'usage': (str,),  # noqa: E501
            'usage_unit': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'account_sid': 'account_sid',  # noqa: E501
        'api_version': 'api_version',  # noqa: E501
        'as_of': 'as_of',  # noqa: E501
        'category': 'category',  # noqa: E501
        'count': 'count',  # noqa: E501
        'count_unit': 'count_unit',  # noqa: E501
        'description': 'description',  # noqa: E501
        'end_date': 'end_date',  # noqa: E501
        'price': 'price',  # noqa: E501
        'price_unit': 'price_unit',  # noqa: E501
        'start_date': 'start_date',  # noqa: E501
        'subresource_uris': 'subresource_uris',  # noqa: E501
        'uri': 'uri',  # noqa: E501
        'usage': 'usage',  # noqa: E501
        'usage_unit': 'usage_unit',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ApiV2010AccountUsageUsageRecordUsageRecordYearly - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            account_sid (str): [optional]  # noqa: E501
            api_version (str): [optional]  # noqa: E501
            as_of (str): [optional]  # noqa: E501
            category (str): [optional]  # noqa: E501
            count (str): [optional]  # noqa: E501
            count_unit (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            end_date (datetime): [optional]  # noqa: E501
            price (float): [optional]  # noqa: E501
            price_unit (str): [optional]  # noqa: E501
            start_date (datetime): [optional]  # noqa: E501
            subresource_uris ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}): [optional]  # noqa: E501
            uri (str): [optional]  # noqa: E501
            usage (str): [optional]  # noqa: E501
            usage_unit (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
