"""
    Twilio - Api

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 1.8.0
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""


import io
import json
import logging
import math
import re
import ssl
from urllib.parse import urlencode, urlsplit, urlunsplit

import urllib3

from openapi_client.exceptions import ApiException, UnauthorizedException, ForbiddenException, NotFoundException, ServiceException, ApiValueError


logger = logging.getLogger(__name__)


_RESPONSE_DATA_UNSET = object()
_HEADER_NAME = re.compile(r"^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$")
_SENSITIVE_REDIRECT_HEADERS = {
    "authorization",
    "cookie",
    "proxy-authorization",
}


def _prepare_request_timeout(value):
    if value is None:
        return None

    def validate_component(component):
        if component is None:
            return
        if (isinstance(component, bool) or
                not isinstance(component, (int, float)) or
                component <= 0 or
                (isinstance(component, float) and
                 not math.isfinite(component))):
            raise ApiValueError(
                "Request timeout values must be positive finite numbers or None."
            )

    if isinstance(value, tuple):
        if len(value) != 2:
            raise ApiValueError(
                "Request timeout tuples must contain connect and read values."
            )
        connect, read = value
        validate_component(connect)
        validate_component(read)
        try:
            return urllib3.Timeout(connect=connect, read=read)
        except (OverflowError, ValueError) as error:
            raise ApiValueError("Request timeout value is invalid.") from error

    validate_component(value)
    try:
        return urllib3.Timeout(total=value)
    except (OverflowError, ValueError) as error:
        raise ApiValueError("Request timeout value is invalid.") from error


def _prepare_response_body_size_limit(value):
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ApiValueError(
            "Response body size limit must be a positive integer."
        )
    return value


def _prepare_retries(value):
    if isinstance(value, urllib3.util.Retry):
        remove_headers = {
            header.lower() for header in value.remove_headers_on_redirect
        }
        remove_headers.update(_SENSITIVE_REDIRECT_HEADERS)
        return value.new(remove_headers_on_redirect=remove_headers)
    return value


def _validate_request_url(url):
    if (not isinstance(url, str) or
            any(ord(char) <= 31 or ord(char) == 127 for char in url)):
        raise ApiValueError("Request URL must be a control-free string.")
    try:
        parsed = urlsplit(url)
        parsed.port
    except ValueError as error:
        raise ApiValueError("Request URL is invalid.") from error
    if parsed.scheme not in ("http", "https") or not parsed.hostname:
        raise ApiValueError("Request URL must use HTTP or HTTPS and include a host.")
    if parsed.username is not None or parsed.password is not None:
        raise ApiValueError("Request URL must not contain userinfo.")


def _validate_request_headers(headers):
    seen_names = {}
    for name, value in headers.items():
        if not isinstance(name, str) or not _HEADER_NAME.fullmatch(name):
            raise ApiValueError("Request header name is invalid.")
        normalized_name = name.lower()
        if normalized_name in seen_names:
            raise ApiValueError(
                "Request headers contain multiple {0} values.".format(
                    seen_names[normalized_name]
                )
            )
        seen_names[normalized_name] = name
        if isinstance(value, bytes):
            invalid = any(byte < 32 and byte != 9 or byte == 127 for byte in value)
        elif isinstance(value, str):
            invalid = any(
                ord(char) < 32 and char != "\t" or ord(char) == 127
                for char in value
            )
        else:
            invalid = False
        if invalid:
            raise ApiValueError("Request header value contains control characters.")


def _is_json_media_type(media_type):
    return media_type == "application/json" or media_type.endswith("+json")


def _read_response_body(response, limit, request_method):
    response_headers = getattr(response, "headers", None)
    if response_headers is None:
        content_length = response.getheader("Content-Length")
        content_encoding = response.getheader("Content-Encoding")
    else:
        content_length = response_headers.get("Content-Length")
        content_encoding = response_headers.get("Content-Encoding")
    try:
        declared_size = int(content_length)
    except (TypeError, ValueError):
        declared_size = None

    encoded_body = (
        isinstance(content_encoding, str) and
        content_encoding.strip().lower() not in ("", "identity")
    )
    if (request_method != "HEAD" and not encoded_body and
            declared_size is not None and declared_size > limit):
        response.close()
        raise ApiException(
            status=response.status,
            reason=(
                "Response body exceeds the configured "
                "{0}-byte limit.".format(limit)
            ),
        )

    try:
        data = bytearray()
        remaining = limit + 1
        while remaining:
            chunk = response.read(amt=remaining, decode_content=True)
            if not chunk:
                break
            data.extend(chunk)
            remaining -= len(chunk)
    except Exception:
        response.close()
        raise

    if len(data) > limit:
        response.close()
        raise ApiException(
            status=response.status,
            reason=(
                "Response body exceeds the configured "
                "{0}-byte limit.".format(limit)
            ),
        )

    response.release_conn()
    return bytes(data)


def _append_query_params(url, query_params):
    if not query_params:
        return url

    parsed = urlsplit(url)
    encoded_params = urlencode(query_params, doseq=True)
    query = parsed.query
    if query:
        query = query + '&' + encoded_params
    else:
        query = encoded_params
    return urlunsplit(
        (parsed.scheme, parsed.netloc, parsed.path, query, parsed.fragment)
    )


def _resolve_content_type(headers):
    content_type_headers = [
        key for key in headers
        if isinstance(key, str) and key.lower() == 'content-type'
    ]
    if len(content_type_headers) > 1:
        raise ApiValueError("Request headers contain multiple Content-Type values.")

    if not content_type_headers:
        headers['Content-Type'] = 'application/json'
        content_type_header = 'Content-Type'
    else:
        content_type_header = content_type_headers[0]

    value = headers[content_type_header]
    if not isinstance(value, str) or not value.strip():
        raise ApiValueError("Content-Type header must be a non-empty string.")

    media_type = value.split(';', 1)[0].strip().lower()
    if not media_type:
        raise ApiValueError("Content-Type header must include a media type.")
    return content_type_header, media_type


class RESTResponse(io.IOBase):

    def __init__(self, resp, data=_RESPONSE_DATA_UNSET):
        self.urllib3_response = resp
        self.status = resp.status
        self.reason = resp.reason
        self.data = resp.data if data is _RESPONSE_DATA_UNSET else data

    def getheaders(self):
        """Returns a dictionary of the response headers."""
        return self.urllib3_response.getheaders()

    def getheader(self, name, default=None):
        """Returns a given response header."""
        return self.urllib3_response.getheader(name, default)


class RESTClientObject(object):

    def __init__(self, configuration, pools_size=4, maxsize=None):
        # urllib3.PoolManager will pass all kw parameters to connectionpool
        # https://github.com/shazow/urllib3/blob/f9409436f83aeb79fbaf090181cd81b784f1b8ce/urllib3/poolmanager.py#L75  # noqa: E501
        # https://github.com/shazow/urllib3/blob/f9409436f83aeb79fbaf090181cd81b784f1b8ce/urllib3/connectionpool.py#L680  # noqa: E501
        # maxsize is the number of requests to host that are allowed in parallel  # noqa: E501
        # Custom SSL certificates and client certificates: http://urllib3.readthedocs.io/en/latest/advanced-usage.html  # noqa: E501

        self.max_response_body_size = _prepare_response_body_size_limit(
            configuration.max_response_body_size
        )

        # cert_reqs
        if configuration.verify_ssl:
            cert_reqs = ssl.CERT_REQUIRED
        else:
            cert_reqs = ssl.CERT_NONE

        addition_pool_args = {}
        if configuration.assert_hostname is not None:
            addition_pool_args['assert_hostname'] = configuration.assert_hostname  # noqa: E501

        if configuration.retries is not None:
            addition_pool_args['retries'] = _prepare_retries(
                configuration.retries
            )

        if configuration.socket_options is not None:
            addition_pool_args['socket_options'] = configuration.socket_options

        if maxsize is None:
            if configuration.connection_pool_maxsize is not None:
                maxsize = configuration.connection_pool_maxsize
            else:
                maxsize = 4

        # https pool manager
        if configuration.proxy:
            self.pool_manager = urllib3.ProxyManager(
                num_pools=pools_size,
                maxsize=maxsize,
                cert_reqs=cert_reqs,
                ca_certs=configuration.ssl_ca_cert,
                cert_file=configuration.cert_file,
                key_file=configuration.key_file,
                proxy_url=configuration.proxy,
                proxy_headers=configuration.proxy_headers,
                **addition_pool_args
            )
        else:
            self.pool_manager = urllib3.PoolManager(
                num_pools=pools_size,
                maxsize=maxsize,
                cert_reqs=cert_reqs,
                ca_certs=configuration.ssl_ca_cert,
                cert_file=configuration.cert_file,
                key_file=configuration.key_file,
                **addition_pool_args
            )

    def request(self, method, url, query_params=None, headers=None,
                body=None, post_params=None, _preload_content=True,
                _request_timeout=None):
        """Perform requests.

        :param method: http request method
        :param url: http request url
        :param query_params: query parameters in the url
        :param headers: http request headers
        :param body: request json body, for `application/json`
        :param post_params: request post parameters,
                            `application/x-www-form-urlencoded`
                            and `multipart/form-data`
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        """
        method = method.upper()
        allowed_methods = {
            'GET', 'HEAD', 'DELETE', 'POST', 'PUT', 'PATCH', 'OPTIONS'
        }
        if method not in allowed_methods:
            raise ApiValueError(
                "Unsupported HTTP method: {0}".format(method)
            )

        if method in ('GET', 'HEAD'):
            if body is not None:
                raise ApiValueError(
                    "GET and HEAD requests cannot include a body."
                )
            if post_params:
                raise ApiValueError(
                    "GET and HEAD requests cannot include form fields."
                )

        if post_params and body is not None:
            raise ApiValueError(
                "body parameter cannot be used with post_params parameter."
            )

        post_params = post_params or {}
        headers = dict(headers or {})

        _validate_request_url(url)
        _validate_request_headers(headers)

        timeout = _prepare_request_timeout(_request_timeout)

        content_type_header, content_type = _resolve_content_type(headers)

        try:
            # For `POST`, `PUT`, `PATCH`, `OPTIONS`, `DELETE`
            if method in ['POST', 'PUT', 'PATCH', 'OPTIONS', 'DELETE']:
                url = _append_query_params(url, query_params)
                if _is_json_media_type(content_type):
                    request_body = None
                    if body is not None:
                        request_body = json.dumps(body)
                    r = self.pool_manager.request(
                        method, url,
                        body=request_body,
                        preload_content=False,
                        timeout=timeout,
                        headers=headers)
                elif content_type == 'application/x-www-form-urlencoded':
                    r = self.pool_manager.request(
                        method, url,
                        fields=post_params,
                        encode_multipart=False,
                        preload_content=False,
                        timeout=timeout,
                        headers=headers)
                elif content_type == 'multipart/form-data':
                    # must del headers['Content-Type'], or the correct
                    # Content-Type which generated by urllib3 will be
                    # overwritten.
                    del headers[content_type_header]
                    r = self.pool_manager.request(
                        method, url,
                        fields=post_params,
                        encode_multipart=True,
                        preload_content=False,
                        timeout=timeout,
                        headers=headers)
                # Pass a `string` parameter directly in the body to support
                # other content types than Json when `body` argument is
                # provided in serialized form
                elif isinstance(body, str) or isinstance(body, bytes):
                    request_body = body
                    r = self.pool_manager.request(
                        method, url,
                        body=request_body,
                        preload_content=False,
                        timeout=timeout,
                        headers=headers)
                else:
                    # Cannot generate the request from given parameters
                    msg = """Cannot prepare a request message for provided
                             arguments. Please check that your arguments match
                             declared content type."""
                    raise ApiValueError(msg)
            # For `GET`, `HEAD`
            else:
                r = self.pool_manager.request(method, url,
                                              fields=query_params,
                                              preload_content=False,
                                              timeout=timeout,
                                              headers=headers)
        except urllib3.exceptions.SSLError as e:
            msg = "{0}\n{1}".format(type(e).__name__, str(e))
            raise ApiException(status=0, reason=msg) from e
        except urllib3.exceptions.HTTPError as e:
            msg = "{0}\n{1}".format(type(e).__name__, str(e))
            raise ApiException(status=0, reason=msg) from e

        if _preload_content:
            try:
                response_data = _read_response_body(
                    r, self.max_response_body_size, method
                )
            except urllib3.exceptions.HTTPError as e:
                msg = "{0}\n{1}".format(type(e).__name__, str(e))
                raise ApiException(status=0, reason=msg) from e

            r = RESTResponse(r, response_data)

            response_size = len(r.data) if r.data is not None else 0
            logger.debug(
                "response received: status=%s bytes=%s",
                r.status,
                response_size,
            )

        if not 200 <= r.status <= 299:
            if not _preload_content:
                streaming_response = r
                r = RESTResponse(streaming_response, None)
                streaming_response.close()
            if r.status == 401:
                raise UnauthorizedException(http_resp=r)

            if r.status == 403:
                raise ForbiddenException(http_resp=r)

            if r.status == 404:
                raise NotFoundException(http_resp=r)

            if 500 <= r.status <= 599:
                raise ServiceException(http_resp=r)

            raise ApiException(http_resp=r)

        return r

    def GET(self, url, headers=None, query_params=None, _preload_content=True,
            _request_timeout=None):
        return self.request("GET", url,
                            headers=headers,
                            _preload_content=_preload_content,
                            _request_timeout=_request_timeout,
                            query_params=query_params)

    def HEAD(self, url, headers=None, query_params=None, _preload_content=True,
             _request_timeout=None):
        return self.request("HEAD", url,
                            headers=headers,
                            _preload_content=_preload_content,
                            _request_timeout=_request_timeout,
                            query_params=query_params)

    def OPTIONS(self, url, headers=None, query_params=None, post_params=None,
                body=None, _preload_content=True, _request_timeout=None):
        return self.request("OPTIONS", url,
                            headers=headers,
                            query_params=query_params,
                            post_params=post_params,
                            _preload_content=_preload_content,
                            _request_timeout=_request_timeout,
                            body=body)

    def DELETE(self, url, headers=None, query_params=None, body=None,
               _preload_content=True, _request_timeout=None):
        return self.request("DELETE", url,
                            headers=headers,
                            query_params=query_params,
                            _preload_content=_preload_content,
                            _request_timeout=_request_timeout,
                            body=body)

    def POST(self, url, headers=None, query_params=None, post_params=None,
             body=None, _preload_content=True, _request_timeout=None):
        return self.request("POST", url,
                            headers=headers,
                            query_params=query_params,
                            post_params=post_params,
                            _preload_content=_preload_content,
                            _request_timeout=_request_timeout,
                            body=body)

    def PUT(self, url, headers=None, query_params=None, post_params=None,
            body=None, _preload_content=True, _request_timeout=None):
        return self.request("PUT", url,
                            headers=headers,
                            query_params=query_params,
                            post_params=post_params,
                            _preload_content=_preload_content,
                            _request_timeout=_request_timeout,
                            body=body)

    def PATCH(self, url, headers=None, query_params=None, post_params=None,
              body=None, _preload_content=True, _request_timeout=None):
        return self.request("PATCH", url,
                            headers=headers,
                            query_params=query_params,
                            post_params=post_params,
                            _preload_content=_preload_content,
                            _request_timeout=_request_timeout,
                            body=body)
